-- Create Database
CREATE DATABASE AuctionSite;
USE AuctionSite;

-- USERS: login accounts (credentials only)
CREATE TABLE Users (
    UserID INT AUTO_INCREMENT PRIMARY KEY,
    Username VARCHAR(50) NOT NULL UNIQUE,
    Email VARCHAR(100) NOT NULL UNIQUE,
    PasswordHash VARCHAR(200) NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- USER PROFILES: personal details for each user
CREATE TABLE UserProfiles (
    ProfileID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT NOT NULL UNIQUE,
    FullName VARCHAR(100),
    Phone VARCHAR(20),
    Address VARCHAR(200),
    Bio VARCHAR(500),
    AvatarUrl VARCHAR(300),
    DateOfBirth DATE,
    CONSTRAINT FK_UserProfiles_User FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE
);

-- CATEGORIES
CREATE TABLE Categories (
    CategoryID INT AUTO_INCREMENT PRIMARY KEY,
    CategoryName VARCHAR(100) NOT NULL UNIQUE
);

-- AUCTIONS
CREATE TABLE Auctions (
    AuctionID INT AUTO_INCREMENT PRIMARY KEY,
    SellerID INT NOT NULL,
    CategoryID INT NOT NULL,
    Title VARCHAR(200) NOT NULL,
    Description TEXT,
    StartingPrice DECIMAL(18,2) NOT NULL,
    CurrentPrice DECIMAL(18,2) NOT NULL,
    StartDate DATETIME NOT NULL,
    EndDate DATETIME NOT NULL,
    Status VARCHAR(20) DEFAULT 'Open',
    CONSTRAINT FK_Auctions_Seller FOREIGN KEY (SellerID) REFERENCES Users(UserID),
    CONSTRAINT FK_Auctions_Category FOREIGN KEY (CategoryID) REFERENCES Categories(CategoryID)
);

-- AUCTION TAGS
CREATE TABLE AuctionTags (
    TagID INT AUTO_INCREMENT PRIMARY KEY,
    AuctionID INT NOT NULL,
    TagName VARCHAR(50) NOT NULL,
    CONSTRAINT FK_Tags_Auction FOREIGN KEY (AuctionID) REFERENCES Auctions(AuctionID) ON DELETE CASCADE
);

-- BIDS
CREATE TABLE Bids (
    BidID INT AUTO_INCREMENT PRIMARY KEY,
    AuctionID INT NOT NULL,
    BidderID INT NOT NULL,
    BidAmount DECIMAL(18,2) NOT NULL,
    BidTime DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_Bids_Auction FOREIGN KEY (AuctionID) REFERENCES Auctions(AuctionID) ON DELETE CASCADE,
    CONSTRAINT FK_Bids_User FOREIGN KEY (BidderID) REFERENCES Users(UserID)
);

-- DEALS
CREATE TABLE Deals (
    DealID INT AUTO_INCREMENT PRIMARY KEY,
    AuctionID INT NOT NULL UNIQUE,
    BuyerID INT NOT NULL,
    SellerID INT NOT NULL,
    FinalPrice DECIMAL(18,2) NOT NULL,
    DealDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_Deals_Auction FOREIGN KEY (AuctionID) REFERENCES Auctions(AuctionID),
    CONSTRAINT FK_Deals_Buyer FOREIGN KEY (BuyerID) REFERENCES Users(UserID),
    CONSTRAINT FK_Deals_Seller FOREIGN KEY (SellerID) REFERENCES Users(UserID)
);

-- MESSAGES
CREATE TABLE Messages (
    MessageID INT AUTO_INCREMENT PRIMARY KEY,
    SenderID INT NOT NULL,
    ReceiverID INT NOT NULL,
    AuctionID INT NULL,
    Content TEXT NOT NULL,
    SentAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_Messages_Sender FOREIGN KEY (SenderID) REFERENCES Users(UserID),
    CONSTRAINT FK_Messages_Receiver FOREIGN KEY (ReceiverID) REFERENCES Users(UserID),
    CONSTRAINT FK_Messages_Auction FOREIGN KEY (AuctionID) REFERENCES Auctions(AuctionID)
);
