spring.application.name=backend
server.port=8081

# ===== DataSource (MySQL) =====
spring.datasource.url=jdbc:mysql://localhost:3306/AuctionSite?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh&characterEncoding=utf8&useUnicode=true
spring.datasource.username=root
spring.datasource.password=1234567
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# ===== OAuth2 Client (Google) =====
spring.security.oauth2.client.registration.google.client-id = 121748365089-p45l8p0u1s6u5vmbtd0vv0fasf99q22t.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret = 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
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.google.client-authentication-method=client_secret_basic
spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code

# Provider mapping (quan trọng để lấy "sub" làm id)
spring.security.oauth2.client.provider.google.user-name-attribute=sub

# ===== App configs =====
app.jwt.secret=K2z9Xn4pQa7wLm0dR8s1Yc5vUf3hJt6B
app.frontend.callback=http://localhost:5174/auth/callback

# thư mục thật trên máy chủ để lưu file
app.upload.dir=uploads

# (tùy chọn) giới hạn size
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=khangnhanopi@gmail.com
spring.mail.password=gvtpfllpdcpommdi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# =========================
# GEMINI API CONFIG
# =========================
gemini.api.base-url=https://generativelanguage.googleapis.com/v1
gemini.api.key=AIzaSyCqSY19DRyMAYVR1fGJQ2yrPIzzO2xXpf4

gemini.model.chat=gemini-2.5-flash

# =========================
# Generation defaults
# =========================
gemini.generation.temperature=0.7
gemini.generation.top-p=0.95
gemini.generation.top-k=40
gemini.generation.max-output-tokens=2048

# =========================
# STRIPE TEST MODE CONFIG
# =========================
stripe.publishable-key=pk_test_51SZQdSPh1XGvhke7YZqMKF9ATy6Eyy7IdTuogul8yH3H84HHEjicTCcfglksXkpAd5jiQVGo9maMXRZHZL1iJjd100LO5D1tRm
stripe.secret-key=sk_test_51SZQdSPh1XGvhke759JLL9TeBKbpzqRFXCM8RcJqIhmej2CZaxrCi65qyFxoRJVOeohAmmRkNilxmeeB8PzC2OpP004pC90XHv
stripe.webhook-secret=whsec_025700d531949c317d5c08bc19bba7730753ea9dea8ae64a5e8f4db216970a06

# (optional) currency & base url
stripe.currency=vnd
stripe.success-url=http://localhost:5174/dashboard/user
stripe.cancel-url=http://localhost:5174/dashboard/user
